name: Deploy Static Application to Ubuntu Apache2 Server
on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:


jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the code
        uses: actions/checkout@v3

      - name: Build Step
        run: echo "Build Step"
      
      - name: Inject Version Details to the Application
        run: |
        sed -i 's/REPLACEAPPLICATIONENVIRONMENT/\$GITHUB_ENV/g' myapp/version.html
        sed -i 's/REPLACEAPPBUILDNO/\$GITHUB_RUN_NUMBER/g' myapp/version.html        

      - name: Upload the Artifact
        uses: actions/upload-artifact@v3
        with:
          name: myapp-package
          part: myapp

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test Step
        run: echo "Test Step"

      - name: Download the Artifact
        uses: actions/download-artifact@v3
        with:
          name: myapp-package
          path: myapp
 
      - name: Verify the downloaded Packages
        run: |
          ls -la
          pwd

      - name: Cat the file and test for replacement
        run: cat myapp/version.html

  deployment:
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 10
    environment:
      name: development
      url: http://20.106.192.145/contact.html

   
    steps:
      # - name: Clone the code
      #   uses: actions/checkout@v3
      - name: Download the myapp-package
        uses: actions/download-artifact@v3
        with:
          name: myapp-package
          path: myapp

      - name: Verify the Code is Cloned
        run: ls -la

      # - name: Copy the Code to the Server
      #   uses: easingthemes/ssh-deploy@main
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
      #     ARGS: "-rltgoDzvO"
      #     SOURCE: "myapp"
      #     REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      #     REMOTE_USER: ${{ secrets.REMOTE_USER }}
      #     TARGET: ${{ secrets.REMOTE_TARGET }}

      # - name: Move the file from Home Directory to Apache Die on Remote Ubuntu Server
      #   uses: appleboy/ssh-action@master
      #   with:
      #      host: ${{ secrets.REMOTE_HOST }}
      #      username: ${{ secrets.REMOTE_USER}}
      #      key: ${{ secrets.SERVER_SSH_KEY}}
      #      port: ${{ secrets.PORT }}
      #      script: sudo mv myapp/* /var/www/html/

      - name: Copy the Index.html to Ubuntu server
        uses: marcodallasanta/ssh-scp-deploy@v1.2.0
        with:
           local: 'myapp'                                                  # Local file path - REQUIRED false - DEFAULT ./
           remote: '/home/azureuser'                                                 # Remote file path - REQUIRED false - DEFAULT ~/
           host: ${{secrets.REMOTE_HOST}}                                      # Remote server address - REQUIRED true
           port: ${{secrets.PORT}}                                      # Remote server port - REQUIRED false - DEFAULT 22
           user: ${{secrets.REMOTE_USER}}                                      # Remote server user - REQUIRED true
           password: ${{secrets.PASSWORD}}                              # User password - REQUIRED at least one of "password" or "key" 
           key: ${{secrets.SERVER_SSH_KEY}}                                      # Remote server private key - REQUIRED at least one of "password" or "key" 
           ARGS: "-rltgoDzvO"
           SOURCE: "myapp"
           pre_upload: echo "remove the files"  # Command to run via ssh before scp upload - REQUIRED false
           post_upload: sudo mv myapp/* /var/www/html/ # Command to run via ssh after scp upload - REQUIRED false
          #  ssh_options: -o StrictHostKeyChecking=no                     # A set of ssh_option separated by -o - REQUIRED false - DEFAULT -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
          #  scp_options: -v  