name: Deploy Static Application to Ubuntu Apache2 Server
on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:


jobs:
 
  deployment:
 
    runs-on: ubuntu-latest
    environment:
      name: development
      url: http://20.106.192.145/contact.html

   
    steps:
      - name: Clone the code
        uses: actions/checkout@v3

      - name: Verify the Code is Cloned
        run: ls -la

      - name: Copy the Code to the Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "myapp"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}

      - name: Move the file from Home Directory to Apache Die on Remote Ubuntu Server
        uses: appleboy/ssh-action@master
        with:
           host: ${{ secrets.REMOTE_HOST }}
           username: ${{ secrets.REMOTE_USER}}
           key: ${{ secrets.SERVER_SSH_KEY}}
           port: ${{ secrets.PORT }}
           script: sudo mv myapp/* /var/www/html/index.html

