name: Deploy Static Application to Ubuntu Apache2 Server
on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:


jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Step
        run: echo "Build Step"

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test Step
        run: echo "Test Step"

  deployment:
 
    runs-on: ubuntu-latest
    environment:
      name: development
      url: http://20.106.192.145/contact.html

   
    steps:
      - name: Clone the code
        uses: actions/checkout@v3

      - name: Verify the Code is Cloned
        run: ls -la

      - name: Copy the Code to the Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "myapp"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}

      - name: Move the file from Home Directory to Apache Die on Remote Ubuntu Server
        uses: appleboy/ssh-action@master
        #with:
           #host: ${{ secrets.REMOTE_HOST }}
           #username: ${{ secrets.REMOTE_USER}}
           #key: ${{ secrets.SERVER_SSH_KEY}}
           #port: ${{ secrets.PORT }}
           #script: sudo mv myapp/* /var/www/html/

        with:
           local: './'                                                  # Local file path - REQUIRED false - DEFAULT ./
           remote: '~/'                                                 # Remote file path - REQUIRED false - DEFAULT ~/
           host: ${{secrets.REMOTE_HOST}}                                      # Remote server address - REQUIRED true
           port: ${{secrets.PORT}}                                      # Remote server port - REQUIRED false - DEFAULT 22
           user: ${{secrets.REMOTE_USER}}                                      # Remote server user - REQUIRED true
           password: ${{secrets.PASSWORD}}                              # User password - REQUIRED at least one of "password" or "key" 
           key: ${{secrets.SERVER_SSH_KEY}}                                      # Remote server private key - REQUIRED at least one of "password" or "key" 
           ARGS: "-rltgoDzvO"
           SOURCE: "myapp"
           pre_upload: echo "This will be executed before the upload!"  # Command to run via ssh before scp upload - REQUIRED false
           post_upload: echo "This will be executed after the upload!"  # Command to run via ssh after scp upload - REQUIRED false
           ssh_options: -o StrictHostKeyChecking=no                     # A set of ssh_option separated by -o - REQUIRED false - DEFAULT -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
           scp_options: -v  